version: "3"

services:
  client:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - '/app/node_modules'
    ports:
    - 3001:3000
    environment:
    - CHOKIDAR_USEPOLLING=true
  server:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - '/app/node_modules'
    ports:
    - 30001:30001
    environment:
    - CHOKIDAR_USEPOLLING=true